### ISSUE TITLE
user parameters .... check and status are the same

### ISSUE THREAD

**Issue by ikzelf** [Open-Future-Belgium/zabbix-barman#2]
Hi Patrik,

in the userparameter_barman.conf is written:
UserParameter=barman.discover,/usr/bin/sudo /usr/share/zabbix-agent/scripts/barman_discovery.py
UserParameter=barman.status[*],/usr/bin/sudo /usr/bin/barman check --nagios $1 | grep OK -c
UserParameter=barman.check[*],/usr/bin/sudo /usr/bin/barman check --nagios $1 | head -1 | grep "$2" -c

1) I think you need to add -u barman to switch from the zabbix agent user to the barman user.
2) for the check I think you meant to do a grep "$2" -c on the complete input instead of just the first line?

thanks for the template,
Ronald.

**Comment by Trikke76** [comment]
Hi Ronald,
thx for the feedback

the -u barman is indeed missing i will add it 

concerning point 2 i will have to check it in our barman setup

in holiday at the moment will fix it and let you know when i am back

thx 
Patrik

**Comment by Trikke76** [comment]
@ikzelf apparently i completely forgot your comment from a few years back
sorry about that.
but apparently you fixed it in your pull request
