### ISSUE TITLE
Steps no so clear

### ISSUE THREAD

**Issue by analuli** [Open-Future-Belgium/zabbix-barman#4]
Hi!

First of all, thank you for the template. Second of all, I've been struggling to set this up as I don't know where I need to make the changes. Could you please help me out?
Your instructions:

In your sudoers file add following option: zabbix ALL=(barman) NOPASSWD: /usr/bin/barman ===> **is this to be modified on the Zabbix Server or on the Barman Server? do I need to add Defaults:zabbix !requiretty also?**

Copy the userparameter_barman.con file to your zabbix agent on the barman server ===> **copy in the folder /etc/zabbix/zabbix_agentd.d/? I think I also have to modify this "/usr/share/zabbix-agent/scripts/" as my external scripts are stored at /usr/lib/zabbix/externalscripts**  

Restart zabbix-agent ===> **in the Barman or Zabbix server?**

Thank you in advance for your help. My Zabbix server is a CentOS 7 server, the version installed is 5.

**Comment by Trikke76** [comment]
hi

In your sudoers file add following option: zabbix ALL=(barman) NOPASSWD: /usr/bin/barman ===> is this to be modified on the Zabbix Server or on the Barman Server? do I need to add Defaults:zabbix !requiretty also?
**this is to be modified on the barman server as the user zabbix need to be able to execute those commands**
** Defaults:zabbix !requiretty ** zabbix agent executes as user zabbix this is to make sure that zabbix can execute sudo withing scripts without the need of a tty 

Copy the userparameter_barman.con file to your zabbix agent on the barman server ===> copy in the folder /etc/zabbix/zabbix_agentd.d/? I think I also have to modify this "/usr/share/zabbix-agent/scripts/" as my external scripts are stored at /usr/lib/zabbix/externalscripts
**the conf files need to be placed in the location where zabbix agent can find them ususally under zabbix_agentd.d but this depends on your agent configuration. the scripts can be copied any where but then you have to change the location also in the userparameter configuration file**

Restart zabbix-agent ===> in the Barman or Zabbix server?

** this needs to be done one the barman server as the agent needs to pick up the configuration changes from the userparameter .conf file **

**Comment by Trikke76** [comment]
btw i am in the progress of reworking the template for zabbix with preprocessing 
will update it soon i hope 
this will improve the performance for barman setups with many postgres instances

**Comment by analuli** [comment]
You are very kind!! Looking forward to this. I will try the steps you have provided. Thank you!!! I will let you know how it went :)

**Comment by analuli** [comment]
Hi!

It is not working :( I receive the following error message:
"Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:
#1) Respect the pri"

I was thinking different possible causes:
* Do I need to install a python interpreter in my Barman server? And then add #!/usr/bin/env python at the beginning of the script?
* Do the permissions play a role? The script has root as owner.
Any other ideas about what to check. I'm running Zabbix agent and server 5.0.3

Thank you in advance for your help.

**Comment by jarlethorsen** [comment]
I have to agree with @analuli here, the readme is rather thin :)

I would suggest adding the xtra information in your answer above to the actual readme on the front page.

What is the current status of this project? I was looking to monitor my barman, but seeing this dangling issue here I am wondering if I would have to fix the issues @analuli has run into before getting this in a working state?

**Comment by Trikke76** [comment]
hi,

i am using it on zabbix 5 without issues
i will update the info page this week with some more info 
but if you copy the scripts to the locations mentioned it should work fine if you give the proper permissions to zabbix agent

**Comment by jarlethorsen** [comment]
Thanks @Trikke76!

This is the first custom template I install for Zabbix, so I didn't want to start out with a template that I had to spend hours debugging.

I'll give it a go then.

And to follow up on your question @analuli ; yes you do need to have python installed on the barman server.

**Comment by jarlethorsen** [comment]
Nice to see you have updated the readme!

However when it comes to the format of the sudoers file:

> Defaults:zabbix !requiretty zabbix ALL=(ALL) NOPASSWD: ALL

This should be split into two lines like this I think?:
```
Defaults:zabbix !requiretty
zabbix ALL=(ALL) NOPASSWD: ALL
```

Probably just have to update the formatting?

**Comment by analuli** [comment]
Thank you both for the comments. I will check the new ReadMe and give it a try again. 
Keep you posted about how it goes.

**Comment by Trikke76** [comment]
fixed it
i will try to upload a agent2 template with preprocessing this week that i have been working on

**Comment by analuli** [comment]
Perfect!! thanks @Trikke76 :) Then I will wait a bit until you upload the new template.
