### ISSUE TITLE
No barman data received?

### ISSUE THREAD

**Issue by jarlethorsen** [Open-Future-Belgium/zabbix-barman#5]
I have followed the instructions in the README.

But still no barman data received from the Ubuntu server where barman and the agent is installed.

I suspect that it may be related to permission-issues on the agent side.

Any suggestion for debugging steps on the agent side?

I'm not seeing anything related to barman in the agent log? (Should there be?)

**Comment by Trikke76** [comment]
well i it possible that your agent is not configured properly a few things you can try:
add all items and discovery rules to zabbix agent not zabbix agent active
try to run the scripts as user zabbix and see if you get output from the scripts

**Comment by jarlethorsen** [comment]
All my agents are passive.

Can you suggest an exact command to run from the commandline on the agent linux machine?

I'm not 100% sure the sudoers stuff is working as expected.

I'm trying to verify that part, but not entirely sure which commands to use.

**Comment by Trikke76** [comment]
root# sudo -u zabbix /usr/bin/sudo -u barman /usr/share/zabbix-agent/scripts/barman_discovery.py

this should return the output in json

check for things like selinux if you have centos/redhat maybe selinux will block things

**Comment by jarlethorsen** [comment]
This is obviously a permission problem:

(however not sure how to solve)

```
user@backup:~$ sudo -u zabbix /usr/bin/sudo -u barman /usr/share/zabbix-agent/scripts/barman_discovery.py
[sudo] password for user: 
sudo: unable to execute /usr/share/zabbix-agent/scripts/barman_discovery.py: Permission denied
```

```
$ ls -l /usr/share/zabbix-agent/scripts/barman_discovery.py
-r-xr-x--- 1 zabbix zabbix 463 Feb 10 09:50 /usr/share/zabbix-agent/scripts/barman_discovery.py
```

**Comment by Trikke76** [comment]
user@backup:~$
that is not the root user ? not sure your user had sudo permissions 
you can give temporary your zabbix user a shell
and run it as the user zabbix 
/usr/bin/sudo -u barman /usr/share/zabbix-agent/scripts/barman_discovery.py

**Comment by jarlethorsen** [comment]
The issue seems to be solved by this pull request:
https://github.com/Open-Future-Belgium/zabbix-barman/pull/6

Now the "Last value" for Barman is "Ok (1)" and all other Barman items have value "Ok (0)"

This is how it is supposed to work I guess?

**Comment by Trikke76** [comment]
ah yes it should have been barman not zabbix

**Comment by Trikke76** [comment]
thx for noticing this
